config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/contact" => "static_pages#contact"
  get "/help" => "static_pages#help"
  get "/about" => "static_pages#about"
  root "static_pages#home"

  get "/signup" => "users#new"
  post "/signup" => "users#create"
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Create a "virtual attribute"
  attr_accessor :remember_token

  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name,
            presence: true,
            length:   { maximum: 50 }
  validates :email,
            presence:   true,
            length:     { maximum: 50 },
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,
            presence: true,
            length:   { minimum: 6 }

  # Returns the hash digest of a given string
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  # Returns true if the given token matches the digest, false otherwise
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  # Forgets a user
  def forget
    update_attribute :remember_digest, nil
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :fetch_user, only: [:create]

  def new; end

  def create
    if @user&.authenticate(params[:session][:password])
      do_login_sequence
    else
      # Use flash.now instead of flash for rendered pages
      flash.now[:danger] = "Invalid email/password combination."
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    flash[:info] = "You have successfully logged out. See you again soon!"
    redirect_to root_url
  end

  private

    def do_login_sequence
      log_in @user
      # Create a persistent session (or not)
      params[:session][:remember_me] == "1" ? remember(@user) : forget(@user)

      redirect_to @user
    end

    def fetch_user
      @user = User.find_by email: params[:session][:email].downcase
    end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def contact; end

  def home; end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = "Thank you for signing up!"
      redirect_to @user
      # this also works
      # redirect to user_url(@user)
      #
    else
      render "new"
    end
  end

  private

    def user_params
      params.require(:user).permit(
        :name, :email, :password, :password_confirmation
      )
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Practice App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in a user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie
  def current_user
    # Old implementation
    # @current_user ||= User.find_by id: session[:user_id]

    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      # if we see a remember cookie and it's authenticated, log that user in
      user = User.find_by id: user_id
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Logs out a user
  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  # Forgets a peristent session
  def forget(user)
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.erb
<footer class="footer">
  <small>
    Copyright &copy; <%= Date.today.year %> Jem Pimentel. All Rights Reserved.
    <%= link_to 'Terms of Use', '#' %> |
    <%= link_to 'Privacy Policy', "#" %>
  </small>
  <nav>
    <ul class="li"><%= link_to 'About', about_path %></ul>
    <ul class="li"><%= link_to 'Contact', contact_path %></ul>
    <ul class="li"><%= link_to 'Site Map', '#' %></ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Practice App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "#{current_user.name}".titlecase, current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": 'reload' %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  <%= render "layouts/shim" %>
  <%= favicon_link_tag "cat.ico" %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
  <% end %>
  <%= yield %>
  <%= render "layouts/footer" %>

  <!--  Debug info-->
  <%= debug params if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize @user.errors.count, "error" %> found.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help
    page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
    Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Practice App</h1>
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt ea eligendi magni mollitia, nihil provident rem
    ut velit? Beatae doloribus est explicabo id nemo nihil obcaecati odio placeat quidem reprehenderit?</h2>
  <%= link_to 'Sign up now', signup_path, class: 'btn btn-lg btn-primary' unless logged_in?%>
</div>
<%= link_to image_tag('rails.png', alt: 'Rails logo'), 'http://www.rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirm your password" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>